### ISSUE TITLE
GS Toast Widget Error

### ISSUE THREAD

**Issue by TheMaskedGuy** [gluestack/gluestack-ui-flutter#100]
GS Toast has an error where it shows blank toast, related to accent variant.
Platform: Mac OS
<img width="780" alt="error-gs-toast" src="https://github.com/gluestack/gluestack-ui-flutter/assets/78201744/4d8a5a1d-4909-4cb0-84b8-ecffc59fd25a">

**Comment by geekruchika** [comment]
Resolved.
